### ISSUE TITLE
2021nen 

### ISSUE THREAD

**Issue by Nekota2TeX** [great-h/5374#25]
2021年1月5日以降のゴミ出しデータが正しく反映されていないように思えます。

大変お手数ですが解決いたしましたらこちらのissueを削除してください。

**Comment by Nekota2TeX** [comment]
広島市中区の地域では確認できています。

**Comment by eiel** [comment]
@Nekota2TeX 
ご回答できていなくて申し訳ないです。
年末やお盆の時期に多い類似の問い合わせ多くありまして、以下の動作の場合は正常な動作です。

* 2020年末の可燃ごみは表示されているが、2021年の可燃ごみが表示されない

5374.jpでは、各種類のゴミについて「次のゴミの日」のみを表示しています。
そのため、2020年の可燃ごみの日が来ていない場合2021年のゴミの日は表示されません。
この仕様なのは、特定の期間のゴミの日を表示するわけではないからです。
たとえば、たまにしか回収のない大型ごみの日が最後に表示されることが多いと思います。その場合、その間の可燃ごみの日をだしてしまうとその間にたくさん表示されてしまうからです。

もしこのような動作ではない場合、バグなのでまたご連絡いただけたら幸いです。
